config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

  resources :comments, only: [:create, :destroy, :edit, :update]
  resources :posts, only: [:index, :show, :create, :destroy, :edit, :update] do
    member do
      post '/like', to: "likes#create", as: "like"
      delete '/like', to: "likes#destroy", as: "unlike"
    end
  end
  post '/follows', to: "follows#create", as: "follow"
  delete '/follows', to: "follows#destroy", as: "unfollow"
  
  get '/profile/:id', to: "users#show", as: "user"
  get '/profile/:id/following', to: "users#followings", as: "following"
  get '/profile/:id/followers', to: "users#followers", as: "followers"
  post '/users/search', to: "users#search", as: :search
  get '/users/search', to: "users#search"
end

app/views/shared/_card-user.html.erb
<div class="row">
  <div class="card user-card">
    <div class="card-content">
      <div class="row">
        <div class="col s2 m2 l2">
          <img src="<%= user.avatar.thumb.url %>" alt="" class="circle responsive-img">
        </div>
        <div class="col s10 m10 l10">
          <div class="row">
            <p class="post-user-name">
              <%= link_to user.name, user_path(user.id) %>
            </p>
          </div>
          <div class="row">
            <p>
              <%= link_to truncate(user.description, length: 150), user_path(user), class: 'grey-text text-darken-2' %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="page-footer">
  <div class="container">
    <div class="copyright">
      <b>
        <a class="copyright-link" href="http://onebitcode.com/">Created with<i class="material-icons copyright-icon">favorite</i> By OneBitCode</a>
      </b>
    </div>
  </div>
</div>

app/views/shared/_list-user.html.erb
<% users.each do |user| %>
  <%= render 'shared/card-user', user: user %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
  <nav class="top-nav">
    <div class="nav-wrapper col s12">
      <div class="container">
        <div class="row">
          <div class="col m3">
            <% if current_user %>
              <a href="/posts" class="brand-logo">
                <i class="material-icons">group</i>
                <span class="logo-title">
                  ProgrammerHub
                </span>
              </a>
            <% else %>
              <a href="/" class="brand-logo">
                <i class="material-icons">group</i>
                <span class="logo-title">
                  ProgrammerHub
                </span>
              </a>
            <% end %>
            <a href="#" data-activates="side-bar" class="button-collapse"><i class="material-icons">menu</i></a>
          </div>

          <ul class="right hide-on-med-and-down">
            <% if current_user %>
              <div class="row">
                <div class="col m7 offset-m3">
                  <li class="search-field">
                    <%= search_form_for @q, url: search_path do |f| %>
                      <%= f.search_field :name_cont, placeholder: "Search.." %>
                    <% end %>
                  </li>
                </div>
                <div class="col m2">
                  <li>
                    <a class="dropdown-button" href="#!" data-activates="dropdown1">
                      <img src="<%= current_user.avatar.thumb.url %>" alt="" class="responsive-img circle nav-image">
                    </a>
                  </li>
                </div>

                <ul id="dropdown1" class="dropdown-content">
                  <li><%= link_to 'Profile', user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Config', edit_user_registration_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
                </ul>
              </div>
            <% else %>
              <li><a href="/users/sign_in">Login</a></li>
              <li><a href="/users/sign_up">Register</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>

<ul class="side-nav" id="side-bar">
  <% if current_user %>
    <li class="search-field">
      <%= search_form_for @q, url: search_path do |f| %>
        <%= f.search_field :name_cont, placeholder: "Search.." %>
      <% end %>
    </li>
    <li><%= link_to 'Feed', posts_path %></li>
    <li><%= link_to 'Profile', user_path(current_user) %></li>
    <li><%= link_to 'Config', edit_user_registration_path(current_user) %></li>
    <li><div class="divider"></div></li>
    <li>  <%= link_to('Log out', destroy_user_session_path, :method => :delete) %></li>
  <% else %>
    <li><a href="/users/sign_in">Log in</a></li>
    <li><div class="divider"></div></li>
    <li><a href="/users/sign_up">Register</a></li>
    <li><div class="divider"></div></li>
  <% end %>
</ul>

app/views/shared/_post.html.erb
<div class="card hoverable" id="post_<%= post.id %>">
  <div class="card-content">
    <div class="row">
      <div class="col s2 m2 l2">
        <img src="<%= post.user.avatar.thumb.url %>" alt="" class="circle responsive-img left">
      </div>
      <div class="col s6 m6 l6">
        <p class="post-user-name"><%= link_to post.user.name, user_path(post.user_id) %></p>
      </div>
      <div class="col s3 m3 l3">
        <b class="post-date"><%= post.created_at.strftime("%Hh%M") %></b>
      </div>
      <% if current_user.id == post.user_id %>
        <div class="col s1 m1 l1">
          <%= link_to post_path(post), method: "delete", remote: true, class: 'delete_post', id: post.id do %>
            <i class="material-icons post-options">delete</i>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col m12">
        <p class="post-body">
          <%= link_to truncate(post.body, length: 2000), post_path(post), class: 'grey-text text-darken-2' %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="post-actions">
        <%= link_to post_path(post) do %>
          <i class='material-icons action-link'>chat_bubble</i> <%= post.comments.count %>
        <% end %>
        <%= link_to unlike_post_path(post), method: "delete", remote: true, class: "unlike unlike_#{post.id}", id: post.id, style: "#{'display:none' unless liked?(current_user, post)}" do %>
          <i class="material-icons liked red-text">favorite</i>
        <% end %>
        <%= link_to like_post_path(post), method: "post", remote: true, class: "like like_#{post.id}", id: post.id, style: "#{'display:none' if liked?(current_user, post)}" do %>
          <i class="material-icons to-like">favorite</i>
        <% end %>
        <span class=<%= "like_count_#{post.id}" %>><%= post.likes.count %></span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user-info.html.erb
<div class="card user-info">
  <div class="card-content">
    <div class="row">
      <div class="user-info">
        <div class="col s4 m2 l4">
          <img src="<%= @user.avatar.thumb.url %>" alt="" class="circle responsive-img">
        </div>
        <div class="col s6 m6 l6">
          <p class="user-name"><%= link_to @user.name, user_path(@user) %></p>
        </div>
        <% if @user.id != current_user.id %>
          <% if current_user.following?(@user) %>
            <div class="col s2 m2 l2">
              <%= link_to unfollow_path(user_id: @user.id), method: :delete do %>
                <i class="material-icons btn-unfollow">grade</i>
              <% end %>
            </div>
          <% else %>
          <div class="col s2 m2 l2">
            <%= link_to follow_path(user_id: @user.id), method: :post do %>
              <i class="material-icons btn-follow">grade</i>
            <% end %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="divider"></div>
    <div class="row activity-info">
      <div class="col s4 m4 l4">
        <p class="center">Followers</p>
        <p class="center p-info"><%= link_to @user.followers_count, followers_path(@user) %></p>
      </div>
      <div class="col s4 m4 l4">
        <p class="center">Following</p>
        <p class="center p-info"><%= link_to @user.follow_count, following_path(@user) %></p>
      </div>
      <div class="col s4 m4 l4">
        <p class="center">Posts</p>
        <p class="center p-info" id="post_count"><%= link_to @user.posts.count, user_path(@user) %></p>
      </div>
    </div>
  </div>
</div>